### ISSUE TITLE
Deliver compiled CSS instead of LESS to reduce browser requirements

### ISSUE THREAD

**Issue by crccheck** [tswicegood/pops#28]
I was trying to use an unconfigured admin form that really should have been using a raw_id_field. As Bootstrap's typeahead.js tried to deal with 40000 rows, I switched to my standard Django admin plan B: disable JavaScript. But the admin site was unusable with JavaScript disabled. This would have worked on the standard Django admin.

**Comment by tswicegood** [comment]
Compiled CSS [is there](https://github.com/tswicegood/pops/blob/master/pops/static/pops/css/style.css) and is used when `DEBUG` is off.

**Comment by crccheck** [comment]
Ah, sorry. I guess I was looking at it locally. That's kind of cool that it does that.

**Comment by tswicegood** [comment]
Thanks.  I thought so, too. :-)
